### ISSUE TITLE
Parse should check for errors before attempting parse

### ISSUE THREAD

**Issue by bedeoverend** [MaxCDN/node-maxcdn#15]
During the [`_parse`](https://github.com/MaxCDN/node-maxcdn/blob/master/index.js#L117) method, it performs a try and catch on parsing the data, then responds with potential errors that happened during the parse _or_ that were handed to it from the request. Because it tries to parse it regardless of incoming errors, it means that if the error didn't have a body attached to it (so body is `undefined`), it will always respond with 'Invalid JSON from MaxCDN\'s API.' even if the error came from the request and was something different.

This is a real pain for debugging - happy to make a PR for this to patch it, as far as I can tell, should just need to do a check for errors and respond if needed before parsing.

**Comment by jdorfman** [comment]
Thanks for the report @bedeoverend. Please make a PR, @jmervine will review and merge it.  Thanks!

**Comment by jmervine** [comment]
Looking at it now. Reply if you're working on / close to having a PR, otherwise I'll have one shortly.

**Comment by bedeoverend** [comment]
This looks to have been fixed in #16 - closing.
