### ISSUE TITLE
Using MaxCDN NodeJS examples produces double slashes in URL

### ISSUE THREAD

**Issue by marcusstenbeck** [MaxCDN/node-maxcdn#17]
`MaxCDN.prototype._makeUrl(p)` will concatenate the string, and if `p` begins with a `/` character the result will be a URL with double slashes. 

So using the example from the MaxCDN API docs

``` js
api.get('/zones.json', function(err, response) {
  console.log('err', err, 'response', response)
})
```

ends up calling `https://rws.maxcdn.com/{companyalias}//zones.json` which returns an error code, while removing the `/` character as follow works fine.

``` js
api.get('zones.json', function(err, response) {
  console.log('err', err, 'response', response)
})
```

See: https://github.com/MaxCDN/node-maxcdn/blob/master/index.js#L63

**Comment by jmervine** [comment]
Thanks for point this out. It would appear the MaxCDN API docs are incorrect, as the docs here show that `api.get('zones.json', ...)` is the correct method. I'll reach out to them and see about getting them updated. Otherwise, perhaps I'll add a quick line to strip any proceeding slashes.

Cheers!
